rm -rf ankalus.git-tools-1.0.0
rm -rf bat
rm -rf clojure
rm -rf coffeescript
rm -rf configuration-editing
rm -rf cpp
rm -rf csharp
rm -rf css
rm -rf css-language-features
rm -rf debug-auto-launch
rm -rf debug-server-ready
rm -rf docker
rm -rf eamodio.gitlens-9.6.3
rm -rf emmet
rm -rf extension-editing
rm -rf fsharp
rm -rf go
rm -rf groovy
rm -rf grunt
rm -rf gulp
rm -rf handlebars
rm -rf hlsl
rm -rf html
rm -rf html-language-features
rm -rf ini
rm -rf jake
rm -rf java
rm -rf json-language-features
rm -rf less
rm -rf log
rm -rf lua
rm -rf make
rm -rf ms-vscode.node-debug
rm -rf ms-vscode.node-debug2
rm -rf ms-vscode.references-view
rm -rf node_modules
rm -rf npm
rm -rf objective-c
rm -rf perl
rm -rf php
rm -rf php-language-features
rm -rf powershell
rm -rf pug
rm -rf r
rm -rf razor
rm -rf ruby
rm -rf rust
rm -rf scss
rm -rf shaderlab
rm -rf shan.code-settings-sync-3.2.9
rm -rf shellscript
rm -rf sql
rm -rf swift
rm -rf theme-abyss
rm -rf theme-kimbie-dark
rm -rf theme-monokai
rm -rf theme-monokai-dimmed
rm -rf theme-red
rm -rf theme-seti
rm -rf theme-solarized-dark
rm -rf theme-solarized-light
rm -rf theme-tomorrow-night-blue
rm -rf typescript-basics
rm -rf typescript-language-features
rm -rf vb
rm -rf xml
rm -rf yaml